In [1]:
import time
from turtle import Turtle

john = Turtle()
print(john)
john.shape("turtle")
john.color("red", "green")
while True:
    john.forward(5)
    john.left(5)
    time.sleep(1)

Terminator: 

In [5]:
f4 = open("test2.txt","r")
print(f4.read())

f4.seek(0)
print(f4.tell())

context = f4.readlines()
print(context)

f4.close()


hello
안녕
반가워
난, 코딩온이야
0
['hello\n', '안녕\n', '반가워\n', '난, 코딩온이야']


In [17]:
#with open("example.txt","a") as file:
  #file.write("\nhi")

with open("example.txt","r") as file:
  #print(file.read())
  for line in file:
    print(line)

hihi

hi

hi

hi

hi

hi

hi


In [16]:
#x는 이미 존재하는 파일은 안걸들고 새로 만들기
with open("new_text.txt","x") as file:
  file.write("This is a new file.")


FileExistsError: [Errno 17] File exists: 'new_text.txt'

In [46]:
for _ in range(3) :
  with open("member.txt", "a") as file :
    file.write(input("아이디 입력")+" ")
    file.write(input("비밀번호 입력") + "\n")

with open("member.txt", "r") as f: 
    line = f.readline()
    while line:
        print(line.strip()) 
        line = f.readline()
  

도파 1
랄로 2
파카 3


In [59]:
A = input("이름을 입력하세요")
B = input("비밀번호를 입력하세요")
with open("member.txt", "r") as f: 
  line = f.readline()
  while (line) :
    if A + " " and B in line.strip():
      print("로그인 성공")
      break
    else :
      print("로그인 실패")
    line = f.readline()

로그인 실패
로그인 실패
로그인 성공


In [68]:
A = input("이름을 입력하세요")
B = input("비밀번호를 입력하세요")
new_mem = input("id"), input("pw")
al_mem = input("id"), input("pw")
with open("member.txt", "r") as f: 
  line = f.readline()
  while (line) :
    if A + " " and B in line.strip():
      with open("member_tel.txt", "a") as file :
        file.write(input("전화번호를 입력하세요")) 
    else:
      print("로그인 실패") 
    line = f.readline()   
    if new_mem in line.strip() :
      with open("member_tel.txt", "a") as file :
        file.write(input("전화번호를 입력하세요")) 
    else:
      print("로그인 실패")
    line = f.readline()  
    if al_mem in line.strip() :
      with open("member_tel.txt", "a") as file :
        file.write(input("전화번호를 입력하세요"))
    else:
      print("로그인 실패")
    line = f.readline()
    
with open("member.txt", "r") as f: 
    line = f.readline()
    while line:
        print(line.strip()) 
        line = f.readline()

with open("member_tel.txt", "r") as file: 
    line_1 = file.readline()
    while line_1:
        print(line_1.strip()) 
        line_1 = file.readline()


TypeError: 'in <string>' requires string as left operand, not tuple

In [69]:
name = input("input name")
pw = input("input pw")
isLogin = False
with open("member.txt","r") as file:
  lines = file.readlines()
  file.seek(0)
  for line in lines:
    text = line.split()# [ name, pw ]
    if len(text) >= 2 and text[0] == name and text[1] == pw:
      isLogin= True
      break
if isLogin:
  print("log in")
else :
  print("log in failed")
if isLogin:
  telNum = input("input tel num")
  with open("member_tel.txt","r+") as file:
    lines = file.readlines()
    file.seek(0)
    for i, line in enumerate(lines): # mylist = ['A', 'B', 'C'] -> (0, 'A'), (1, 'B'), (2,'C')
      text = line.split()
      if text and text[0] == name:
        lines[i] = f"{name} {telNum}\n"
        break
    else:
      lines.append(f"{name} {telNum}\n")
    file.writelines(lines)

log in


In [76]:

while (1) :
  A = input("정수")
  try :  
    A == int(A)
    print("정답")
    break
  except ValueError :
    print("정수를 입력하세요.")

  

정수를 입력하세요.
정수를 입력하세요.
정수를 입력하세요.
정답


In [80]:
import numpy as np

A = [[1,2], [1,2]]
B = [[1,2], [1,2]]
np.matmul(A,B)


array([[3, 6],
       [3, 6]])

In [1]:
import numpy as np

zero_array = np.zeros(10)
print(zero_array)

zero_array[4] = 1
print(zero_array)

A_array = np.arange(10,31)
print(A_array)

random_array = np.random.randint(0,100,(2,2))
print(random_array)

C_array = np.random.rand(2,4)
print(C_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[ 7 90]
 [77  8]]
[[0.97379414 0.96136595 0.13258734 0.16454334]
 [0.90395585 0.09894395 0.32447984 0.66935168]]


In [4]:
import numpy as nb

asd = nb.arange(35,75)
asd.shape = (10,4)
#print(asd)

ads = asd[::-1]
#print(ads)

A = asd[1:-1, 2:]
#print(A)

B = asd[:,3]
#print(B)

B_1 = asd[:,3:]
#print(B_1)

C = asd[::-1, 3::]
#print(C)

D = nb.random.randint(1,51,(5,6))
print(D)
D[D%2 == 0]

[[38 18 14 44  8 33]
 [32  5 43 37 49 17]
 [37 46 24 14 24 14]
 [30 50 11  1 43 33]
 [24  7  3 36  6  5]]


array([38, 18, 14, 44,  8, 32, 46, 24, 14, 24, 14, 30, 50, 24, 36,  6])

In [14]:
import numpy as np

A = [1, 1, 2, 3, 4, 5, 5, 5, 5, 7, 8, 9, 10, 11, 24, 100]
#1
A_unique = np.unique(A)
print(A_unique)
#2
A_max = np.max(A_unique)
A_min = np.min(A_unique)
A_mean = np.mean(A_unique)
print(A_max, A_min, A_mean)
#3
A_sum = np.sum(A_unique)
print(A_sum)
#4
A_median = np.median(A)
print(A_median)

[  1   2   3   4   5   7   8   9  10  11  24 100]
100 1 15.333333333333334
184
5.0
